# Enable Display
CONFIG_ZMK_DISPLAY=y

# Increase memory for LVGL v9 + ZMK Studio
CONFIG_LV_Z_MEM_POOL_SIZE=16384

# Isolate the display thread (Fixes the pulse)
CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y

# Reduce screen update frequency to save CPU/Battery
# (30fps is plenty for a keyboard)
CONFIG_ZMK_DISPLAY_FRAME_RATE_LIMIT=30

# Force a full clear every 5 minutes to prevent ghosting
CONFIG_ZMK_DISPLAY_FULL_REFRESH_PERIOD=300